-- 테이블 생성
CREATE TABLE IF NOT EXISTS TBL_ADMINMENU (
    ID UUID NOT NULL, -- TBL_ADMIN.ID 참조
    USERID VARCHAR(50) NOT NULL,
    UNIVINFO JSONB NOT NULL, -- { "univcd": "0001", "univnm": "대학1", "term": "KU" }
    MENU JSONB NOT NULL,     -- ["01","02","03"]
    MODIFYDATE VARCHAR(14),
    MODIFYID VARCHAR(50),
    MODIFYIP VARCHAR(15),
    CONSTRAINT TBL_ADMINMENU_pkey PRIMARY KEY (ID),
    CONSTRAINT fk_tbl_admin FOREIGN KEY (ID) REFERENCES TBL_ADMIN(ID) ON DELETE CASCADE
) TABLESPACE KUWAY;

ALTER TABLE IF EXISTS TBL_ADMINMENU OWNER TO dev1;

-- 주석
COMMENT ON TABLE TBL_ADMINMENU IS '관리자 계정별 접근 가능 메뉴 테이블';

COMMENT ON COLUMN TBL_ADMINMENU.ID IS 'UUID 기본키 (TBL_ADMIN ID)';
COMMENT ON COLUMN TBL_ADMINMENU.USERID IS '유저 아이디';
COMMENT ON COLUMN TBL_ADMINMENU.UNIVINFO IS '소속 대학 정보(JSON: {univcd, univnm, term})';
COMMENT ON COLUMN TBL_ADMINMENU.MENU IS '접근 가능 메뉴(JSON: ["01","02","03"])';
COMMENT ON COLUMN TBL_ADMINMENU.MODIFYDATE IS '수정 일자 (YYYYMMDDHHMMSS)';
COMMENT ON COLUMN TBL_ADMINMENU.MODIFYID IS '수정 USERID';
COMMENT ON COLUMN TBL_ADMINMENU.MODIFYIP IS '수정 IP';