-- 테이블 생성
CREATE TABLE IF NOT EXISTS TBL_ADMIN (
    ID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    USERID VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    USERNM VARCHAR(100),
    HTEL VARCHAR(13),
    EMAIL VARCHAR(50),
    IP VARCHAR(15),
    GRADE VARCHAR(5),
    PARTCD VARCHAR(5),
    PARTNM VARCHAR(100),
    UNIVCD VARCHAR(4),
    UNIVNM VARCHAR(100),
    SMSYN VARCHAR(1),
    EMAILYN VARCHAR(1),
    LOGINDATE VARCHAR(14),
    PWDDATE VARCHAR(14),
    MODIFYDATE VARCHAR(14),
    MODIFYID VARCHAR(50),
    MODIFYIP VARCHAR(15),
    CONSTRAINT TBL_ADMIN_pkey PRIMARY KEY (ID) USING INDEX TABLESPACE KUWAY
) TABLESPACE KUWAY;

ALTER TABLE IF EXISTS TBL_ADMIN OWNER TO dev1;

COMMENT ON TABLE TBL_ADMIN IS '관리자 테이블 생성';

-- 컬럼 주석
COMMENT ON COLUMN TBL_ADMIN.ID IS 'UUID 기본키 (자동 생성)';
COMMENT ON COLUMN TBL_ADMIN.USERID IS '유저 아이디';
COMMENT ON COLUMN TBL_ADMIN.PASSWORD IS '유저 패스워드';
COMMENT ON COLUMN TBL_ADMIN.USERNM IS '유저 이름';
COMMENT ON COLUMN TBL_ADMIN.HTEL IS '유저 연락처';
COMMENT ON COLUMN TBL_ADMIN.EMAIL IS '유저 메일';
COMMENT ON COLUMN TBL_ADMIN.IP IS '유저 아이피';
COMMENT ON COLUMN TBL_ADMIN.GRADE IS '계정 권한';
COMMENT ON COLUMN TBL_ADMIN.PARTCD IS '업무 구분 코드';
COMMENT ON COLUMN TBL_ADMIN.PARTNM IS '업무 구분명';
COMMENT ON COLUMN TBL_ADMIN.UNIVCD IS '소속 대학 코드';
COMMENT ON COLUMN TBL_ADMIN.UNIVNM IS '소속 대학 명';
COMMENT ON COLUMN TBL_ADMIN.SMSYN IS '문자 발송 여부 (Y/N)';
COMMENT ON COLUMN TBL_ADMIN.EMAILYN IS '메일 발송 여부 (Y/N)';
COMMENT ON COLUMN TBL_ADMIN.LOGINDATE IS '최근 접속 일자 (YYYYMMDDHHMMSS)';
COMMENT ON COLUMN TBL_ADMIN.PWDDATE IS '최근 패스워드 변경 일자 (YYYYMMDDHHMMSS)';
COMMENT ON COLUMN TBL_ADMIN.MODIFYDATE IS '최근 수정 일자 (YYYYMMDDHHMMSS)';
COMMENT ON COLUMN TBL_ADMIN.MODIFYID IS '최근 수정자 아이디';
COMMENT ON COLUMN TBL_ADMIN.MODIFYIP IS '최근 수정자 아이피';

