-- TBL_MNGMENU: 관리자 계정별 접근 가능 메뉴 마스터
CREATE TABLE IF NOT EXISTS TBL_MNGMENU (
    ID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    MENUCD VARCHAR(5) NOT NULL,
    MENUNM VARCHAR(100) NOT NULL,
    CONSTRAINT TBL_MNGMENU_pkey PRIMARY KEY (ID) USING INDEX TABLESPACE KUWAY,
    CONSTRAINT TBL_MNGMENU_menucd_uk UNIQUE (MENUCD)
) TABLESPACE KUWAY;

ALTER TABLE IF EXISTS TBL_MNGMENU OWNER TO dev1;

-- 주석
COMMENT ON TABLE TBL_MNGMENU IS '관리자 계정별 접근 가능 메뉴 테이블';
COMMENT ON COLUMN TBL_MNGMENU.ID IS 'UUID 기본키 (자동 생성)';
COMMENT ON COLUMN TBL_MNGMENU.MENUCD IS 'MENU CODE (실제 웹 라우트/페이지 코드 등)';
COMMENT ON COLUMN TBL_MNGMENU.MENUNM IS '웹에서 보여지는 메뉴 명';

