// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/login": {
    params: {};
  };
  "/api/refresh-token": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/api/login" | "/api/refresh-token";
  };
  "./view/login.jsx": {
    id: "view/login";
    page: "/";
  };
  "./api/login.js": {
    id: "api/login";
    page: "/api/login";
  };
  "./api/refresh-token.js": {
    id: "api/refresh-token";
    page: "/api/refresh-token";
  };
};